const DEFAULT_AVATAR = 'http://tva3.sinaimg.cn/crop.0.0.180.180.180/7f5f6861jw1e8qgp5bmzyj2050050aa8.jpg'
const SERVICE_AVATAR = 'http://tva3.sinaimg.cn/crop.0.0.180.180.180/7f5f6861jw1e8qgp5bmzyj2050050aa8.jpg';
const USER_AVATAR = '/src/avatar/user.png';

const MODE_SERVICE = 'askForService'
const MODE_QUESTION = 'askRobot'

const TYPE_USER = 'C'
const TYPE_SERVICE = 'S'

const MSG_TYPE_CHAT = 'C';
const MSG_TYPE_GROUP = 'G';
const MSG_TYPE_SYSTEM = 'S';
const MSG_TYPE_COMMAND = 'M';
const MSG_TYPE_BROADCAST = 'B';
const MSG_TYPE_TOALL = 'A';
const MSG_TYPE_QUESTION = 'Q';

const CONTENT_TYPE_TEXT = 'text';
const CONTENT_TYPE_FILE = 'file';
const CONTENT_TYPE_IMAGE = 'image';
const CONTENT_TYPE_REGISTER = 'register';
const CONTENT_TYPE_READ = 'read';
const CONTENT_TYPE_READGROUP = 'readGroup';
const CONTENT_TYPE_SERVICE = 'service';

const CONTENT_TYPE_OFFLINE = 'offline';
const CONTENT_TYPE_ASKFORSERVICE = 'askForService';
const CONTENT_TYPE_ASKROBOT = 'askRobot';
const CONTENT_TYPE_NOTICE = 'notice';
const CONTENT_TYPE_FORM = 'form';
const CONTENT_TYPE_PUSH_FORM = 'pushForm';
const CONTENT_TYPE_OVER = 'over';

export default {
  DEFAULT_AVATAR,
  SERVICE_AVATAR,
  USER_AVATAR,  
  MODE_SERVICE,
  MODE_QUESTION,
  TYPE_USER,
  TYPE_SERVICE,
  MSG_TYPE_CHAT,
  MSG_TYPE_GROUP,
  MSG_TYPE_SYSTEM,
  MSG_TYPE_COMMAND,
  MSG_TYPE_BROADCAST,
  MSG_TYPE_TOALL,
  MSG_TYPE_QUESTION,
  CONTENT_TYPE_TEXT,
  CONTENT_TYPE_FILE,
  CONTENT_TYPE_IMAGE,
  CONTENT_TYPE_REGISTER,
  CONTENT_TYPE_READ,
  CONTENT_TYPE_READGROUP,
  CONTENT_TYPE_SERVICE,
  CONTENT_TYPE_OFFLINE,
  CONTENT_TYPE_ASKFORSERVICE,
  CONTENT_TYPE_ASKROBOT,
  CONTENT_TYPE_NOTICE,
  CONTENT_TYPE_FORM,
  CONTENT_TYPE_PUSH_FORM,
  CONTENT_TYPE_OVER,
}
